### PR TITLE
The Sprite Yeet PR (ie safely remove sprites)

### LINKED ISSUE #23: Animations don't adjust for deleted sprites
Trying to delete any sprites results in other sprites having their indexes shifted, and the animations don't account for this. This causes animations to have the wrong sprites, and uncaught exceptions to be thrown endlessly if an animation with an invalid sprite index is selected.
image

### PR DESCRIPTION
**Pull request by patataofcourse**
Fixes #23. Also adds a small confirmation dialogue when replacing a sprite that is being used in any animations.
image

### CODE REVIEW

File: src/main/kotlin/rhmodding/bread/editor/SpritesTab.kt [hunk 1]
```diff
@@ -127,9 +127,38 @@ open class SpritesTab<F : IDataModel>(editor: Editor<F>) : EditorSubTab<F>(edito
...
                                 alert.contentText = "Are you sure you want to remove this sprite?\nYou won't be able to undo this action."
+
                                 if (alert.showAndWait().get() == ButtonType.OK) {
-                                    editor.removeSprite(currentSprite)
-                                    updateSpriteSpinners(false)
+                                    // Check every step because at this point we don't know if the sprite is used in any anims
+                                    var cancel = false
+                                    val index = data.sprites.indexOf(currentSprite).toUShort()
+                                    for (anim in data.animations) {
+                                        var isbreak = true
```
Comment (CebolaBros64) [inline src/main/kotlin/rhmodding/bread/editor/SpritesTab.kt:136]: Should be `false`, otherwise the for loop breaks after checking the first animation and the second dialogue box doesn't appear regardless of the sprite being present in an animation or not (sprite is still deleted)

**Review by CebolaBros64 — CHANGES_REQUESTED** [review]

**Comment by CebolaBros64** [comment]
Implementation-wise everything seems to check out. Apart from the change I requested as a comment, I have a few more suggestions to the UX side of things:

- As of right now, the title of the alert window only tells the user the index of the animation. I believe this isn't very useful to the end user, and that having the animation's name in place would make more sense. (Ex.: "Sprite used in animation rishiki_beat_blue")
- It feels redundant to have two alerts confirming that the sprite is going to be deleted. Just one alert is fine.

BTW, you may also add yourself to the list in `rhmodding/bread/utils/Credits.kt` if you feel so inclined 🎉

File: src/main/kotlin/rhmodding/bread/editor/SpritesTab.kt (hunk 1 above)
Comment (patataofcourse) [reply src/main/kotlin/rhmodding/bread/editor/SpritesTab.kt:136]: how did i not notice that XD

**Comment by patataofcourse** [comment]
Okay, I'll add all these changes and lyk when it's done
